print("Mi\nnombre\nes\nBond.", end=" ")
print("James Bond.")
print()
print("fish", "chips", sep="&")
print()
print('Greg\'s book.')
print("'Greg's book.'")
print('"Greg\'s book."')
print("Greg\'s book.")
print('"Greg's book."')
